[project]
name = "inbox-cast"
version = "0.1.0"
description = "Convert inbox emails into PodCast"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.0.0",
    "google-auth-httplib2>=0.1.0",
    "google-auth-oauthlib>=1.0.0"
]
